vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_profile_image:
            uri_prefix: /images/profile_images
            upload_destination: '%kernel.project_dir%/public/images/profile_images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

